#If you do not specify a service account, it is automatically assigned the "default" service account in the same namespace
#Create Service Account with sufficient permission 

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: app1-ns
  name: app1-cron-runner
rules:
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["patch", "get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app1-cron-runner
  namespace: app1-ns
subjects:
- kind: ServiceAccount
  name: app1-sa-cron-runner
  namespace: app1-ns
roleRef:
  kind: Role
  name: app1-cron-runner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1-sa-cron-runner
  namespace: app1-ns