kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: app1-ns
  name: app1-cron-runner
rules:
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["patch", "get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: app1-cron-runner
  namespace: app1-ns
subjects:
- kind: ServiceAccount
  name: app1-sa-cron-runner
  namespace: app1-ns
roleRef:
  kind: Role
  name: app1-cron-runner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1-sa-cron-runner
  namespace: app1-ns