#  Apply resources from a directory containing kustomization.yaml - e.g. dir/kustomization.yaml
#  kubectl apply -k mongo/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app1-Deployment.yml
  - app1-Service.yml
  - app1-Ingress.yml